package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseAgentUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentUser extends BaseAgentUser<AgentUser> {
	{}
}
