package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseBlogroll;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blogroll extends BaseBlogroll<Blogroll> {
	
}
