package com.autu.common.model.entity;

import java.util.List;

import com.autu.common.model.entity.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")

public class Comment extends BaseComment<Comment> {
	private List<Comment> childs;
	
	private AgentUser user;
	
 
	public Integer getPageNum() {
		return getInt("pageNum");
	}

	public void setPageNum(Integer pageNum) {
		if(pageNum==0) {
			pageNum=1;
		}
 
		this.put("pageNum", pageNum);
	}

	public List<Comment> getChilds() {
		if(childs==null) {
			childs=new Comment().find("select * from comment where parentId=? and isAduit=1",getId());
		}
		return childs;
	}

	public void setChilds(List<Comment> childs) {
		this.childs = childs;
	}

	public AgentUser getUser() {
		if(user==null) {
			user=new AgentUser().findById(getToUserId());
		}
		return user;
	}

	public void setUser(AgentUser user) {
		this.user = user;
	}
	
	
}
