package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	
}
