package com.autu.common.model.entity;

import com.autu.common.model.dto.Social;
import com.autu.common.model.entity.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	
	private Social social=new Social();

	public Social getSocial() {
		return social;
	}

	public void setSocial(Social social) {
		this.social = social;
	}
	
	
}
