package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseRelevancy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relevancy extends BaseRelevancy<Relevancy> {
	
}
