package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseThemeConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThemeConfig extends BaseThemeConfig<ThemeConfig> {
	
}
