package com.autu.common.model.entity;

import com.autu.common.model.entity.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
}
