package com.autu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccessLog<M extends BaseAccessLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}
	
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}
	
	public java.lang.String getCookie() {
		return getStr("cookie");
	}

	public void setInfo(java.lang.String info) {
		set("info", info);
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public void setUserAgent(java.lang.String userAgent) {
		set("userAgent", userAgent);
	}
	
	public java.lang.String getUserAgent() {
		return getStr("userAgent");
	}

	public void setAgentUserId(java.lang.Integer agentUserId) {
		set("agentUserId", agentUserId);
	}
	
	public java.lang.Integer getAgentUserId() {
		return getInt("agentUserId");
	}

}
