package com.autu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSeo<M extends BaseSeo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPattern(java.lang.String pattern) {
		set("pattern", pattern);
		return (M)this;
	}
	
	public java.lang.String getPattern() {
		return getStr("pattern");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setOther(java.lang.String other) {
		set("other", other);
		return (M)this;
	}
	
	public java.lang.String getOther() {
		return getStr("other");
	}

	public M setRelId(java.lang.Integer relId) {
		set("relId", relId);
		return (M)this;
	}
	
	public java.lang.Integer getRelId() {
		return getInt("relId");
	}

}
