package com.autu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLoginRecord<M extends BaseLoginRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setSessionId(java.lang.String sessionId) {
		set("sessionId", sessionId);
		return (M)this;
	}
	
	public java.lang.String getSessionId() {
		return getStr("sessionId");
	}

	public M setDevice(java.lang.String device) {
		set("device", device);
		return (M)this;
	}
	
	public java.lang.String getDevice() {
		return getStr("device");
	}

	public M setIsValid(java.lang.Boolean isValid) {
		set("isValid", isValid);
		return (M)this;
	}
	
	public java.lang.Boolean getIsValid() {
		return get("isValid");
	}

}
