package com.autu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDisk<M extends BaseDisk<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSize(java.lang.Long size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public M setGmtModify(java.util.Date gmtModify) {
		set("gmtModify", gmtModify);
		return (M)this;
	}
	
	public java.util.Date getGmtModify() {
		return get("gmtModify");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setThumbUrl(java.lang.String thumbUrl) {
		set("thumbUrl", thumbUrl);
		return (M)this;
	}
	
	public java.lang.String getThumbUrl() {
		return getStr("thumbUrl");
	}

	public M setHash(java.lang.String hash) {
		set("hash", hash);
		return (M)this;
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

}
