package com.autu.common.model;

import com.autu.common.model.base.BaseLoginRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginRecord extends BaseLoginRecord<LoginRecord> {
	
}
