package com.autu.common.model;

import com.autu.common.model.base.BaseMetaweblogConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MetaweblogConfig extends BaseMetaweblogConfig<MetaweblogConfig> {
	
}
