package com.autu.common.model;

import com.autu.common.model.base.BaseMetaweblogRelevance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MetaweblogRelevance extends BaseMetaweblogRelevance<MetaweblogRelevance> {
	
}
