package com.autu.common.model;

import com.autu.common.model.base.BaseOperateLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperateLog extends BaseOperateLog<OperateLog> {
	
}
