package com.autu.common.model;

import com.autu.common.model.base.BasePage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Page extends BasePage<Page> {
	
	private static Article articleDao=new Article().dao();
	
	private Article article;

	private String content;
	
	
	
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Article getArticle() {
		if(article!=null) {
			return article;
		}
		
		if(getArticleId()==null) {
			return null;
		}
		
		setArticle(articleDao.findById(getArticleId()));
		
		return article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}
	
	
}
