package com.autu.common.model;

import com.autu.common.model.base.BaseRelevancy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relevancy extends BaseRelevancy<Relevancy> {
	
}
