package com.autu.common.model;

import java.util.List;

import com.autu.common.model.base.BaseRouteMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RouteMenu extends BaseRouteMenu<RouteMenu> {
	
	private List<Route> children;
	
	/**
	 * 获取子项
	 * @return
	 */
	public List<Route> getChildren(){
		if(children!=null) {
			return children;
		}
		children= Route.dao.find("select * from route where parentId=? and isDeleted=0",getId());
		
		if(children.isEmpty()) {
			return children;
		}
		
		children.forEach( route ->{
			 route.setParentId(getId());
		});
		
		return children;
	}
	
}
