package com.autu.common.model;

import com.autu.common.model.base.BaseRoute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Route extends BaseRoute<Route> {
	
	private static Article articleDao=new Article().dao();
	
	public Article article;

	public Article getArticle() {
		if(article!=null) {
			return article;
		}
		
		if(getArticleId()==null) {
			return null;
		}
		
		setArticle(articleDao.findById(getArticleId()));
		
		return article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}
	
	
}
