package com.autu.common.model;

import com.autu.common.model.base.BaseRoute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Route extends BaseRoute<Route> {
	
	public static Route dao=new Route().dao();
 
 
}
