package com.autu.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setICPRecord(java.lang.String ICPRecord) {
		set("ICPRecord", ICPRecord);
		return (M)this;
	}
	
	public java.lang.String getICPRecord() {
		return getStr("ICPRecord");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public M setEmailServer(java.lang.String emailServer) {
		set("emailServer", emailServer);
		return (M)this;
	}
	
	public java.lang.String getEmailServer() {
		return getStr("emailServer");
	}

	public M setFromEmail(java.lang.String fromEmail) {
		set("fromEmail", fromEmail);
		return (M)this;
	}
	
	public java.lang.String getFromEmail() {
		return getStr("fromEmail");
	}

	public M setEmailPassword(java.lang.String emailPassword) {
		set("emailPassword", emailPassword);
		return (M)this;
	}
	
	public java.lang.String getEmailPassword() {
		return getStr("emailPassword");
	}

	public M setIco(java.lang.String ico) {
		set("ico", ico);
		return (M)this;
	}
	
	public java.lang.String getIco() {
		return getStr("ico");
	}

	public M setLogo(java.lang.String logo) {
		set("logo", logo);
		return (M)this;
	}
	
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public M setQiniuAk(java.lang.String qiniuAk) {
		set("qiniuAk", qiniuAk);
		return (M)this;
	}
	
	public java.lang.String getQiniuAk() {
		return getStr("qiniuAk");
	}

	public M setQiniuSk(java.lang.String qiniuSk) {
		set("qiniuSk", qiniuSk);
		return (M)this;
	}
	
	public java.lang.String getQiniuSk() {
		return getStr("qiniuSk");
	}

	public M setQiniuBucket(java.lang.String qiniuBucket) {
		set("qiniuBucket", qiniuBucket);
		return (M)this;
	}
	
	public java.lang.String getQiniuBucket() {
		return getStr("qiniuBucket");
	}

	public M setQiniuUrl(java.lang.String qiniuUrl) {
		set("qiniuUrl", qiniuUrl);
		return (M)this;
	}
	
	public java.lang.String getQiniuUrl() {
		return getStr("qiniuUrl");
	}

	public M setIsAuditComment(java.lang.Boolean isAuditComment) {
		set("isAuditComment", isAuditComment);
		return (M)this;
	}
	
	public java.lang.Boolean getIsAuditComment() {
		return get("isAuditComment");
	}
}
